name: "CI Tests"

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.can-fail }}
    name: "PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }}${{ matrix.composer-flags != '' && format(' - Composer {0}', matrix.composer-flags) || '' }}"
    strategy:
      matrix:
        include:
          - { os: ubuntu-20.04, php: 7.2, symfony: "5.4.*", composer-flags: "--prefer-stable --prefer-lowest", can-fail: false }
          - { os: ubuntu-latest, php: 8.3, symfony: "6.4.*", composer-flags: "--prefer-stable", can-fail: false }
          - { os: ubuntu-latest, php: 8.2, symfony: "6.3.*", composer-flags: "--prefer-stable", can-fail: false }
          - { os: ubuntu-latest, php: 8.2, symfony: "6.4.*", composer-flags: "--prefer-stable", can-fail: false }
          - { os: ubuntu-latest, php: 8.3, symfony: "7.0.*", composer-flags: "--prefer-stable", can-fail: false }

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 2

      - name: "Cache Composer packages"
        uses: "actions/cache@v3"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php }}-symfony-${{ matrix.symfony }}-composer-${{ hashFiles('composer.json') }}-flags-${{ matrix.composer-flags }}"
          restore-keys: "php-"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          tools: "composer:v2,flex"

      - name: Install dependencies
        run: composer update ${{ matrix.composer-flags }} --prefer-dist
        env:
          SYMFONY_REQUIRE: "${{ matrix.symfony }}"

      - name: Run PHPUnit Tests
        run: composer test
