name: "CI Tests"

on:
  pull_request:
  push:

env:
  fail-fast: true
  PHPUNIT_FLAGS: "-v"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: PHP v${{ matrix.php }}, Symfony v${{ matrix.symfony }}, ${{ matrix.dependencies }} version
    strategy:
      matrix:
        include:
          - { os: ubuntu-latest, php: 7.4, symfony: "5.4.*", dependencies: "lowest"}
          - { os: ubuntu-latest, php: 7.4, symfony: "5.4.*", dependencies: "stable"}
          - { os: ubuntu-latest, php: 8.1, symfony: "5.4.*", dependencies: "lowest"}
          - { os: ubuntu-latest, php: 8.1, symfony: "5.4.*", dependencies: "stable"}
          - { os: ubuntu-latest, php: 8.2, symfony: "5.4.*", dependencies: "stable"}
          - { os: ubuntu-latest, php: 8.0, symfony: "6.3.*@dev", dependencies: "lowest"}
          - { os: ubuntu-latest, php: 8.0, symfony: "6.3.*@dev", dependencies: "stable"}
          - { os: ubuntu-latest, php: 8.1, symfony: "6.3.*@dev", dependencies: "stable"}
          - { os: ubuntu-latest, php: 8.2, symfony: "6.3.*@dev", dependencies: "stable"}

    steps:
      - uses: actions/checkout@v2
      - name: "Installing php"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl,mbstring,xdebug
          ini-values: date.timezone="Europe/Paris"
          coverage: xdebug
          tools: composer
      - name: Show PHP version
        run: php -v && composer -V

      - name: Download Composer cache dependencies from cache
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.os }}-composer-

      - name: Set Composer stability
        if: matrix.symfony == '6.3.*@dev'
        run: composer config minimum-stability dev

      - name: Install dependencies
        run: |
          composer update --no-interaction --prefer-${{ matrix.dependencies }} --prefer-dist --no-progress
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}

      - name: Run PHPUnit Tests
        run: composer test
